version: '3'

services:
  frontendui:
    build: frontend
    ports:
      - 8501:8501
    volumes:
      - './frontend:/app:delegated'
    depends_on:
      - service

  service:
    build: service
    ports:
      - 8000:8000